# Generated by Django 5.2.4 on 2025-07-28 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_files_alter_order_status_alter_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='files',
        ),
        migrations.AddField(
            model_name='files',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.product'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
